_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.6
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 20
learning_rate:
    value: 0.0001
model:
    value: ResNet18
optimizer:
    value: AdamW
weight_decay:
    value: 1e-05
