name: Model Development Pipeline

on:
  push:
    branches:
      - main  # Trigger action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger action for pull requests targeting the main branch

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out your code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Set your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt  # Install dependencies from requirement.txt
        pip install papermill  # Install papermill for executing Jupyter notebooks

  train_model:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the setup job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install papermill

    - name: Execute Jupyter Notebook
      run: |
        papermill trashnet-ResNet18.ipynb output_train_model.ipynb  # Execute the notebook and save the output

    - name: Save model output
      run: |
        mkdir -p model_output
        cp output_train_model.ipynb model_output/  # Optional: Store output notebook for debugging/insights
        cp trained_model.pth model_output/  # Move the trained model to a separate folder

  upload_model:
    runs-on: ubuntu-latest
    needs: train_model  # This job depends on the train_model job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install huggingface_hub
      run: |
        python -m pip install huggingface_hub

    - name: Upload model to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Retrieve the Hugging Face token from GitHub Secrets
      run: |
        echo "${HF_TOKEN}" | huggingface-cli login --token
        huggingface-cli upload model_output/trained_model.pth --repo_id hadi2894/trashnet-resnet18
